basePath: /
definitions:
  ds.AddToAssemblyID:
    properties:
      autopart:
        $ref: '#/definitions/ds.AutopartDetails'
      user_id:
        type: integer
    type: object
  ds.Assembly:
    properties:
      creator_id:
        type: integer
      date_end:
        type: string
      date_processing:
        type: string
      date_start:
        type: string
      description:
        type: string
      factory:
        type: string
      factory_id:
        type: integer
      status:
        type: string
    type: object
  ds.AssemblyDetails:
    properties:
      assembly:
        $ref: '#/definitions/ds.Assembly'
      autoparts:
        items:
          $ref: '#/definitions/ds.Autopart'
        type: array
    type: object
  ds.AssemblyForm:
    properties:
      factory_id:
        type: integer
      user_id:
        type: integer
    type: object
  ds.Autopart:
    properties:
      autopart_id:
        type: integer
      brand:
        type: string
      description:
        type: string
      image:
        type: string
      is_deleted:
        type: boolean
      model:
        type: string
      name:
        type: string
      price:
        type: number
      user_id:
        type: integer
      year:
        type: integer
    type: object
  ds.Autopart_Assembly:
    properties:
      autopart_factory_id:
        type: integer
      autopart_id:
        type: integer
      count:
        type: integer
      factory_id:
        type: integer
    type: object
  ds.AutopartDetails:
    properties:
      autopart_id:
        type: integer
      name:
        type: string
    type: object
  ds.AutopartList:
    properties:
      autoparts_list:
        items:
          $ref: '#/definitions/ds.Autopart'
        type: array
      draft_id:
        type: integer
    type: object
  ds.UserLogin:
    properties:
      login:
        maxLength: 64
        type: string
      password:
        maxLength: 64
        minLength: 4
        type: string
    required:
    - login
    - password
    type: object
  ds.UserSignUp:
    properties:
      login:
        maxLength: 64
        type: string
      name:
        type: string
      password:
        maxLength: 64
        minLength: 4
        type: string
    required:
    - login
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: App for serving autoparts requests
  title: Autoparts App
  version: "1.0"
paths:
  /api/assembly:
    delete:
      consumes:
      - application/json
      description: Delete Assembly by admin
      parameters:
      - description: Delete Assembly
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.AssemblyForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Assembly'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete Assembly by admin
      tags:
      - Assembly
    put:
      consumes:
      - application/json
      description: Update Assembly by admin
      parameters:
      - description: updated Assembly
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.Assembly'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Assembly'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update Assembly by admin
      tags:
      - Assembly
  /api/assembly/complete:
    put:
      consumes:
      - application/json
      description: Complete Assembly by admin
      parameters:
      - description: Complete Assembly
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.AssemblyForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Assembly'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Complete Assembly by admin
      tags:
      - Assembly
  /api/assembly/form:
    put:
      consumes:
      - application/json
      description: Form Assembly by client
      parameters:
      - description: Form Assembly
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.AssemblyForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Assembly'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Form Assembly by client
      tags:
      - Assembly
  /api/assembly/get-al:
    get:
      consumes:
      - application/json
      description: Assembly List
      parameters:
      - description: Query string to filter Assemblies by status
        in: query
        name: status
        type: string
      - description: Query string to filter Assemblies from start date
        in: query
        name: start
        type: string
      - description: Query string to filter Assemblies to end date
        in: query
        name: end
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.Assembly'
            type: array
        "400":
          description: Bad Request
          schema: {}
      summary: Assembly List
      tags:
      - Assembly
  /api/assembly/reject:
    put:
      consumes:
      - application/json
      description: Reject Assembly by admin
      parameters:
      - description: Reject Assembly
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.AssemblyForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Assembly'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Reject Assembly by admin
      tags:
      - Assembly
  /api/assembly{id}:
    get:
      consumes:
      - application/json
      description: Assembly By ID
      parameters:
      - description: Assembly ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.AssemblyDetails'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: server error
          schema: {}
      summary: Assembly By ID
      tags:
      - Assembly
  /api/autoparts:
    post:
      consumes:
      - application/json
      description: Add Autopart by admin
      parameters:
      - description: New autopart
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.Autopart'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema: {}
      summary: Add Autopart by admin
      tags:
      - Autoparts
    put:
      consumes:
      - application/json
      description: Update Autopart by admin
      parameters:
      - description: updated autopart
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.Autopart'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Autopart'
        "400":
          description: Bad Request
          schema: {}
      summary: Update Autopart by admin
      tags:
      - Autoparts
  /api/autoparts/add-to-assembly:
    post:
      consumes:
      - application/json
      description: Add To Assembly by client
      parameters:
      - description: Add To Assembly autopart
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.AddToAssemblyID'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema: {}
      summary: Add To Assembly by client
      tags:
      - Autoparts
  /api/autoparts/get-al:
    get:
      consumes:
      - application/json
      description: Autoparts List
      parameters:
      - description: Query string to filter autoparts by name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.AutopartList'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Autoparts List
      tags:
      - Autoparts
  /api/autoparts/upload-image:
    post:
      consumes:
      - multipart/form-data
      description: Add Image to autopart by admin
      parameters:
      - description: autopart ID
        in: formData
        name: id
        type: integer
      - description: image
        in: formData
        name: image
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Add Image to autopart by admin
      tags:
      - Autoparts
  /api/autoparts_assembly:
    delete:
      consumes:
      - application/json
      description: Delete Autopart From Assembly by client
      parameters:
      - description: Delete Autopart From Assembly
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.Autopart_Assembly'
      produces:
      - application/json
      responses:
        "200":
          description: deleted successfully
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete Autopart From Assembly by client
      tags:
      - Autopart_Assembly
    put:
      consumes:
      - application/json
      description: Update Count Autopart Assembly by client
      parameters:
      - description: Delete Autopart From Assembly
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.Autopart_Assembly'
      produces:
      - application/json
      responses:
        "200":
          description: updated successfully
          schema:
            $ref: '#/definitions/ds.Autopart_Assembly'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update Count Autopart Assembly by v
      tags:
      - Autopart_Assembly
  /api/autoparts{id}:
    delete:
      consumes:
      - application/json
      description: Delete Autopart by admin
      parameters:
      - description: Autoaprt ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete Autopart by admin
      tags:
      - Autoparts
    get:
      consumes:
      - application/json
      description: Autopart By ID
      parameters:
      - description: Autoaprt ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Autopart'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Autopart By ID
      tags:
      - Autoparts
  /api/user/logout:
    post:
      consumes:
      - application/json
      description: Logs out the user by blacklisting the access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Logout
      tags:
      - Authentication
  /api/user/signIn:
    post:
      consumes:
      - application/json
      description: Authenticates a user and generates an access token
      parameters:
      - description: User information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/ds.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: User sign-in
      tags:
      - Authentication
  /api/user/signUp:
    post:
      consumes:
      - application/json
      description: Creates a new user account
      parameters:
      - description: User information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/ds.UserSignUp'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema: {}
        "409":
          description: Conflict
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Sign up a new user
      tags:
      - Authentication
schemes:
- http
swagger: "2.0"
